# Stage 1: Python
FROM python:3.7
ENV PYTHONPATH /code

RUN mkdir /code
WORKDIR /code
RUN pip install pipenv uwsgi

COPY . .
RUN pipenv install --system --deploy
RUN chmod +x docker-entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["./docker-entrypoint.sh"]
